GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzMyMjEwNTQsImV4cCI6MTczMzIyMTA3OSwiYXVkIjoiNjc0ZDkzNDY2OGQyMDE1YzFlMWQ1NmYyIiwiaXNzIjoicGlja3VwLmNvbSJ9.ERY7TDGCtHleJ787TXQGWKbi9Y855bBkBPmMlGz_xC0


### Register route ###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "thakare2@gmail.com",
  "password": "thakare2"
}

### login route ###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "thakare1@gmail.com",
  "password": "thakare1"
}

### Refresh-Token route ###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzMyMjEwMjUsImV4cCI6MTc2NDc3ODYyNSwiYXVkIjoiNjc0ZDkzNDY2OGQyMDE1YzFlMWQ1NmYyIiwiaXNzIjoicGlja3VwLmNvbSJ9.-ltZ3uCC-7Tmdj0Nm9saUL63a3uDdz-AN7Hlx0Z67rY"
}

### logout route ###
delete http://localhost:3000/auth/logout