GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzMxMzk1NTUsImV4cCI6MTczMzE5MzU1NSwiYXVkIjoiNjc0ZDkzNDY2OGQyMDE1YzFlMWQ1NmYyIiwiaXNzIjoicGlja3VwLmNvbSJ9.3akxQCcLlMw5kly71mMER4JpqP-r1KPNgLS_ug94nU4


### Register route ###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "thakare1@gmail.com",
  "password": "thakare1"
}

### login route ###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "thakare1@gmail.com",
  "password": "thakare1"
}

### Refresh-Token route ###
POST http://localhost:3000/auth/refresh-token

### logout route ###
delete http://localhost:3000/auth/logout